version: '3'
services:
  db_chat:
    image: postgres
    volumes:
      - postgres_database_chat:/var/lib/postgresql/data
    ports:
      - "5437:5437"
  web_chat:
    build: .
    command: bundle exec rails s -p 3012 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3012:3012"
    depends_on:
      - db_chat
volumes:
    postgres_database_chat:
        external: true
